apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bucketlist-app
  name: bucketlist-app
  namespace: bucketlist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bucketlist-app
  template:
    metadata:
      labels:
        app: bucketlist-app
    spec:
      containers:
      - name: app
        image: localhost:5000/bucketlist-app:latest
        env:
          - name: CosmosDB__Account
            valueFrom:
              secretKeyRef:
                key: Account
                name: cosmos-settings
                optional: false
          - name: CosmosDB__Key
            valueFrom:
              secretKeyRef:
                key: Key
                name: cosmos-settings
                optional: true
          - name: CosmosDB__DatabaseName
            valueFrom:
              secretKeyRef:
                key: DatabaseName
                name: cosmos-settings
                optional: true
          - name: CosmosDB__ContainerName
            valueFrom:
              secretKeyRef:
                key: ContainerName
                name: cosmos-settings
                optional: true
        ports:
        - containerPort: 80
          name: webserver
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
      terminationGracePeriodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: bucketlist-service
  namespace: bucketlist
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: bucketlist-app
